### ISSUE TITLE
Define backend API

### ISSUE THREAD

**Issue by sarahdagger** [ubclaunchpad/floradora#16]
Consider what endpoints the backend will need to expose for the frontend to interact with. These could be things such as an image upload endpoint, an endpoint to get collection data, etc. No coding necessary for this task - instead, let's document the interface in a Google doc so we can discuss it as a team.

**Comment by allwelly** [comment]
I wrote some things down on the doc, let me now if I need to put in more details to it, you can ignore the note because it's just there as a reminder for me. I'll get working on issue #17 once I get an ok on this, thanks!
link to [backend doc](https://docs.google.com/document/d/1OYaDkZv_8E2lBw62o4McuSR80OeNbdt3fIywvOk3jW4/edit)

**Comment by sarahdagger** [comment]
API specs located in the new [backend doc](https://docs.google.com/document/d/1OdrQ2OuRg3XPLFFexH2r4DyFAe5WQNEZbezAL8xaAoA/edit#heading=h.628q3713jz9r)
